<?php

/**
 * @file
 * Module hooks and alters for Admin UI customizations.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function sitestudio_gin_preprocess_page(&$variables) {
  // Global CSS overrides.
  $variables['#attached']['library'][] = 'sitestudio_gin/sitestudio_gin-global-overrides';

  // Overrides only if Gin is the active theme.
  $theme = \Drupal::theme()->getActiveTheme()->getName();
  if ($theme == 'gin') {
    $variables['#attached']['library'][] = 'sitestudio_gin/sitestudio_gin-gin-overrides';

    $route = \Drupal::routeMatch()->getRouteName();
    if ($route == 'sitestudio-page-builder.layout_canvas.frontend_edit_component'
      && !empty($variables['page']['gin_secondary_toolbar'])) {
      // Remove the gin secondary toolbar from the Site Studio iframe.
      unset($variables['page']['gin_secondary_toolbar']);
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for \Drupal\cohesion_elements\Form\ComponentContentForm.
 *
 * Changes vertical tabs to container.
 *
 * Note: Adapted from cohesion_elements_form_component_content_edit_form_alter()
 * for gin admin theme.
 *
 * @see cohesion_elements_form_component_content_edit_form_alter()
 * @see claro_form_node_form_alter()
 */
function sitestudio_gin_form_component_content_edit_form_alter(&$form, FormStateInterface $form_state) {
  $theme = \Drupal::theme()->getActiveTheme()->getName();

  if ($theme == 'gin') {
    $form['#theme'] = ['node_edit_form'];
    $form['#attached']['library'][] = 'claro/node-form';

    $form['advanced']['#type'] = 'container';
    $form['advanced']['#accordion'] = TRUE;
    $form['meta']['#type'] = 'container';
    $form['meta']['#access'] = TRUE;
    $form['meta']['changed']['#wrapper_attributes']['class'][] = 'container-inline';
    $form['meta']['author']['#wrapper_attributes']['class'][] = 'container-inline';

    $form['revision_information']['#type'] = 'container';
    $form['revision_information']['#group'] = 'meta';
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for \ Drupal\cohesion_elements\Form\ComponentContentForm.
 *
 * Changes vertical tabs to container.
 *
 * Note: Adapted from cohesion_elements_form_component_content_edit_form_alter()
 * for gin admin theme.
 *
 * @see sitestudio_gin_form_component_content_edit_form_alter()
 */
function sitestudio_gin_form_component_content_add_form_alter(&$form, FormStateInterface $form_state) {
  sitestudio_gin_form_component_content_edit_form_alter($form, $form_state);
}

/**
 * Implements hook_gin_content_form_routes().
 *
 * Register routes to apply the Gin content edit form layout.
 */
function sitestudio_gin_gin_content_form_routes() {
  return [
    // Layout a component content using node form.
    'entity.component_content.add_form',
    'entity.component_content.edit_form',
  ];
}
